### PR TITLE
Add disappearing effect when temporary power up is about to expire

### LINKED ISSUE #85: Make temp powerup (armor effect) flash when nearing expiry

### PR DESCRIPTION
**Pull request by beatricetay**
- Modified Default Effect blueprint to add a 'TriggerDisappearEffectAfterXSeconds' event, that toggles the visibility of the effect on and off after X seconds.
- It is called by the player when the player creates an effect.

- I felt like this invocation from the player blueprint was needed, as the player currently controls the duration of the temporary effects

Fixes #85

### CODE REVIEW

**Review by raniceyue — DISMISSED** [review]

**Comment by iskandarzulkarnaien** [comment]
Hihi, just tested and it looks good. I just wanna check what was changed in DefaultGameMap and TestEffectMap? Are those changes intended to be checked in (its common for accidental checking in of map files).

Also can I check what was changed in the powerup blueprints themselves?

**Review by iskandarzulkarnaien — CHANGES_REQUESTED** [review]
Requested changes listed in prior comment

**Comment by beatricetay** [comment]
> Hihi, just tested and it looks good. I just wanna check what was changed in DefaultGameMap? Are those changes intended to be checked in (its common for accidental checking in of map files).
> 
> Also can I check what was changed in the powerup blueprints themselves?

Hihi, Idt anything was changed in the defaultgamemap, my bad!
For the powerup blueprints, I duplicated the powerup materials, put them in the same folder, and changed the materials for the powerups. Just to make it more consistent with some of the material names. e.g. M_Prism is used for just the prism

**Review by iskandarzulkarnaien — APPROVED** [review]
LGTM, thanks for making the requested changes :D

**Pull request merged**
