### PR TITLE
Local Multiplayer

### PR DESCRIPTION
**Pull request by beatricetay**
## Changes made
- Added local multiplayer functionality to the LocalMultiplayerGameMap
  1. Players can be registered by pressing 'Enter' on the keyboard or pressing 'Options'/'Start' on the Gamepad
  2. Players can be unregistered by pressing 'Backspace' on the keyboard or 'Share'/'Back' on the Gamepad
  3. You can then click 'Start game' to start the game
  4. Keyboard players can use WASD to move and space to shoot and Esc to pause. Gamepad players can use the left joystick/ the left arrow keys on the gamepad to move, and the circle / the B button to shoot.
  5. The game would spawn AI bots in the slots that were not taken by human players
  6.  The game will end if there are no longer any human players alive, or if there is only 1 human player remaining

### Files affected:

>         new file:   Content/Blueprints/Multiplayer/BP_BeamermanLocalMultiplayerGameMode.uasset
>         new file:   Content/Blueprints/Multiplayer/BP_Multiplayer_Controller.uasset
>         new file:   Content/Blueprints/Multiplayer/TempCharacterSelectionWidget.uasset
>         new file:   Content/LocalMultiplayerGameMap.umap
>         new file:   Content/UI/HUD/MultiplayerGameWidgetHUD.uasset

>         modified:   Config/DefaultEngine.ini                   // Remove auto mapping of Gamepad controller 1 to player controller 0
>         modified:   Config/DefaultInput.ini                      // Add mapping for the RegisterPlayer/UnregisterPlayer button and the gamepad joystick movements
>         modified:   Content/Blueprints/Player/BP_BeamermanPlayer.uasset // Add another cast to BP_BeamermanLocalMultiplayerGameMode for the "player die" part
>         modified:   Content/PersistentGameInstance.uasset // Add some other properties that the multiplayer game needs to store

## Todo
- [x] Change the player registration HUD (Current HUD is just a bunch of rectangles)
- [x] Disable BEGIN BATTLE button if < 1 player controllers detected
- [ ] Test with 4 controllers (I tested with 1 keyboard and 3 controllers, because my 4th controller is not responding to my PC :( )
- [x] ~~(Later): Register players based on the time the player clicks the 'start' button, instead of permanently assigning gamepad X to slot X~~ **To be implemented in separate PR**

## ‼‼ Bugs
- [x] For some reason game music still plays after the mayhem mode has started
- [x] P1 P2 skins in the controller detection are swapped
- [x] ~~Game ends prematurely when there are 2 players remaining in mayhem mode~~ (Unable to recreate, I think previously, the AI might have walked off the platform and I didnt realise it)
- [x] LAG! FPS drops about 60 on the local multiplayer map
- [x] After lighting build, texture for the player controller detection platform just disappears
- [x] Lighting in the player controller detection scene is messed up

### CODE REVIEW

**Review by raniceyue — DISMISSED** [review]

**Comment by raniceyue** [comment]
### Audio Refactor
- Removed all audio components from the level maps
- Moved the audio controls to game instance. From now on when we want to start or stop some audio, have to `Get Game Instance -> Cast to PersistantGameInstance ->` then call functions defined in the game instance to start or stop the audio accordingly.

I did this refactor because it would be better if the main menu BGM could carry on into the multiplayer level as it would be weird to have the level BGM during the controller detection part of the level. Also, it would be better for controlling audio in the future when we want to manipulate the BGM and SFX via the menus in the future.

**Comment by raniceyue** [comment]
## Implement controller detection UI
Because the controller detection is within the level map itself, above the arena, there is a big black box above the arena that acts as the scene for the controller detection interface before the game starts. 

### Controller Detection Scene
Within this box, there are 4 dummy players and a separate camera which the multiplayer level will start with initially. Once a controller is detected, the corresponding player's player number label + platform the character is standing on will light up (see below image)

image

In this scene, the main menu music continues on (suppose you access the multiplayer level from the main menu level)

Once the player presses the **BEGIN BATTLE** button, the camera will switch (and fade to black), and the music will transition to that of the game music.

## For Discussion
### Restart Button Behaviour
Upon pressing restart game, the whole level will be re-loaded. This means that the players have to do the controller detection scene all over again. There are 2 use cases for the restart button in this context
   1. The players want to restart the entire level in order to re-do the controller detection etc.
   2. The players want to restart the game only 
I am not sure what the behaviour of the restart button should be in this case because the above 2 use cases would require 2 different functionalities altogether

**Review by gachia — DISMISSED** [review]
LGTM (tested with 1 KBM and 1 Controller, don't have more than that). Although is it possible to change the Fire button to **A** instead of **B**? **A** button is usually the default button in games to do something. It helps players to intuitively play the game even if they didn't read the controls.

**Comment by raniceyue** [comment]
> 
> 
> LGTM (tested with 1 KBM and 1 Controller, don't have more than that). Although is it possible to change the Fire button to **A** instead of **B**? **A** button is usually the default button in games to do something. It helps players to intuitively play the game even if they didn't read the controls.

We can change this in a diff PR? Also what do you think about the restart buttion behaviour that I mentioned in an earlier comment?

**Comment by gachia** [comment]
> > LGTM (tested with 1 KBM and 1 Controller, don't have more than that). Although is it possible to change the Fire button to **A** instead of **B**? **A** button is usually the default button in games to do something. It helps players to intuitively play the game even if they didn't read the controls.
> 
> We can change this in a diff PR? Also what do you think about the restart buttion behaviour that I mentioned in an earlier comment?

Alright. Behaviour number 2 would probably be the best. Reassigning the controllers would require them going back to the main menu entirely.

**Comment by raniceyue** [comment]
### Changes Made
- Fix fade between cameras issue
- Added back scene captures to the local multiplayer map
- Make <kbd>Esc</kbd> button during multiplayer selection go back to the main menu map instead of opening the pause menu (when opening the pause menu, players still able to press begin game)

**Review by gachia — APPROVED** [review]
new changes LGTM

**Pull request merged**
