### PR TITLE
[WIP] Online multiplayer bug fix final

### PR DESCRIPTION
**Pull request by raniceyue**
## To-do
- [x] Fix bug for when host dies, all the players become player 1
- [x] Fix bugs for when other players die, host score becomes 0
(Above completed to @beatricetay)
- [x] Camera swap still visible
- [x] Once game starts, host must be removed from lobby 

## Changes Made
- Created powerup icon for explode-o-mat
- Updated the armour powerups to look more like what they really are
- Updated the how to play screen

### CODE REVIEW

**Comment by raniceyue** [comment]
As of latest commit before this comment, successfully managed to resolve issue #215 
image

**Comment by raniceyue** [comment]
Implemented defeat screen for clients with options to spectate or leave the game to go back to the lobby

**Review by beatricetay — COMMENTED** [review]
lgtm

**Review by beatricetay — APPROVED** [review]
lgtm

**Pull request merged**
