### PR TITLE
AI improvements

### PR DESCRIPTION
**Pull request by irene-lly**
- created task for AI to calculate and use laser reflections
- rewrote all other tasks
- remodeled entire behavior tree
- removed coupling between AI controller and mirror 
- removed print statements, random debug lines , etc.

Try winning the game : )

### CODE REVIEW

**Comment by gachia** [comment]
image
I managed to beat the AI! They respond much better now. I lost a couple of games because they were too good sometimes.

**Comment by gachia** [comment]
I did find a bug however. In one of the game, the explosive barrel, which is spawned from a powerup, spawned directly on top one of the AI players. Even though the barrel has no collision, the AI got stuck, being unable to move around or attack. I only saw it change the direction of which it was facing.
(Sorry no screenshots, I wanted to take one but I pressed the wrong button and close the instance)

**Comment by irene-lly** [comment]
Okay, I've figured out why:
the AI can only walk in the green areas, as can be seen from the pic, the AI cannot walk through the barrels
image

So that might have caused it to be stucked in a location.

So I have unticked this in BP_ExplosiveBarrel:
image

and yah the area under the barrels is now green
image

**Review by gachia — DISMISSED** [review]
LGTM

**Review by iskandarzulkarnaien — APPROVED** [review]
LGTM

**Pull request merged**
