### PR TITLE
Victory HUD logic

### PR DESCRIPTION
**Pull request by raniceyue**

### CODE REVIEW

**Comment by raniceyue** [comment]
## Changes Made
- Added logic to victory screen
- Fixed scaling issues, currently does not work for portrait type screens where height >> width

**Comment by raniceyue** [comment]
### Update
- Fixed low quality images for victory screen, now victory screen shows HD captures of each player's static mesh

**Comment by iskandarzulkarnaien** [comment]
Lets leave the refactoring for another time, we should focus on the main polish of the game for now given the limited time frame we have left.

**Comment by raniceyue** [comment]
### Update 
- Add scene capture blueprints to main map, previously when they were not in the map, need to open all blueprints for the texture to be captured
- Fix bugs in textures

### To Note
- Because of the map lighting, the scene captures of the skeletal meshes of each character look a bit faded out
- I am not sure if adding the scene capture is slowing down performace of the game, when I test it out in editor, it plays smoothly however when I create a shipping build, the shipping build gameplay is a bit laggy

### To Do
- Fix minor scaling issues for the victory screen
- Add drone count to HUD 
- Remove HUD before showing victory screen

Someone please let me know if I should do the to-do stuff in a sparate PR

**Review by J-Dan23 — APPROVED** [review]
LGTM

**Review by iskandarzulkarnaien — APPROVED** [review]

**Pull request merged**
